#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PerformanceRole

#include "Basic.hpp"

#include "EPerformanceRoleState_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "SPerformanceRoleInfo_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "KuroAnim_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_PerformanceRole.ABP_PerformanceRole_C
// 0x6C70 (0x74A0 - 0x0830)
class UABP_PerformanceRole_C : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0830(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0838(0x0138)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0970(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0990(0x0020)()
	struct FAnimNode_RBF                          AnimGraphNode_RBF;                                 // 0x09B0(0x0150)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x0B00(0x0038)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0B38(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_113;                // 0x0B70(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_112;                // 0x0B98(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_111;                // 0x0BC0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_110;                // 0x0BE8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_109;                // 0x0C10(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_108;                // 0x0C38(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_107;                // 0x0C60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_106;                // 0x0C88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_105;                // 0x0CB0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_104;                // 0x0CD8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_103;                // 0x0D00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_102;                // 0x0D28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_101;                // 0x0D50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_100;                // 0x0D78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_99;                 // 0x0DA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_98;                 // 0x0DC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_97;                 // 0x0DF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_96;                 // 0x0E18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_95;                 // 0x0E40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_94;                 // 0x0E68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_93;                 // 0x0E90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_92;                 // 0x0EB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_91;                 // 0x0EE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_90;                 // 0x0F08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_89;                 // 0x0F30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_88;                 // 0x0F58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_87;                 // 0x0F80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_86;                 // 0x0FA8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_85;                 // 0x0FD0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_84;                 // 0x0FF8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_83;                 // 0x1020(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_82;                 // 0x1048(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_81;                 // 0x1070(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_80;                 // 0x1098(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_79;                 // 0x10C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_78;                 // 0x10E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_77;                 // 0x1110(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_76;                 // 0x1138(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_75;                 // 0x1160(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_74;                 // 0x1188(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_73;                 // 0x11B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_72;                 // 0x11D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_71;                 // 0x1200(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_70;                 // 0x1228(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_69;                 // 0x1250(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_68;                 // 0x1278(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_67;                 // 0x12A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_66;                 // 0x12C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_65;                 // 0x12F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_64;                 // 0x1318(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_63;                 // 0x1340(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_62;                 // 0x1368(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_61;                 // 0x1390(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_60;                 // 0x13B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_59;                 // 0x13E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_58;                 // 0x1408(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_34;                   // 0x1430(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_53;                      // 0x1508(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_33;                   // 0x1540(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_52;                      // 0x1618(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_57;                 // 0x1650(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_32;                   // 0x1678(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_51;                      // 0x1750(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_56;                 // 0x1788(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_55;                 // 0x17B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_54;                 // 0x17D8(0x0028)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_13;          // 0x1800(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_12;          // 0x1940(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult_6;            // 0x1A80(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_53;                 // 0x1AB8(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_5;                 // 0x1AE0(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_50;                      // 0x1B58(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31;                   // 0x1B90(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_49;                      // 0x1C68(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_30;                   // 0x1CA0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_48;                      // 0x1D78(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_11;                     // 0x1DB0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_47;                      // 0x1F48(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_52;                 // 0x1F80(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_29;                   // 0x1FA8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_46;                      // 0x2080(0x0038)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x20B8(0x0060)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_28;                   // 0x2118(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_45;                      // 0x21F0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_10;                     // 0x2228(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_44;                      // 0x23C0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_51;                 // 0x23F8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_27;                   // 0x2420(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_43;                      // 0x24F8(0x0038)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x2530(0x0060)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_26;                   // 0x2590(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_42;                      // 0x2668(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_9;                      // 0x26A0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_41;                      // 0x2838(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_50;                 // 0x2870(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25;                   // 0x2898(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_40;                      // 0x2970(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_49;                 // 0x29A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_48;                 // 0x29D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_47;                 // 0x29F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_46;                 // 0x2A20(0x0028)()
	uint8                                         Pad_2A48[0x8];                                     // 0x2A48(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_11;          // 0x2A50(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_10;          // 0x2B90(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult_5;            // 0x2CD0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_45;                 // 0x2D08(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_39;                      // 0x2D30(0x0038)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x2D68(0x0060)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24;                   // 0x2DC8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_38;                      // 0x2EA0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23;                   // 0x2ED8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_37;                      // 0x2FB0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_8;                      // 0x2FE8(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_36;                      // 0x3180(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22;                   // 0x31B8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_35;                      // 0x3290(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44;                 // 0x32C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x32F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x3318(0x0028)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_9;           // 0x3340(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_8;           // 0x3480(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult_4;            // 0x35C0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x35F8(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_4;                 // 0x3620(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_34;                      // 0x3698(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x36D0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_33;                      // 0x37A8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x37E0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_32;                      // 0x38B8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_7;                      // 0x38F0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_31;                      // 0x3A88(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x3AC0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x3AE8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x3B10(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x3B38(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x3B60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x3B88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x3BB0(0x0028)()
	uint8                                         Pad_3BD8[0x8];                                     // 0x3BD8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_7;           // 0x3BE0(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_6;           // 0x3D20(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult_3;            // 0x3E60(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x3E98(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x3EC0(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_3;                 // 0x3EE8(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_30;                      // 0x3F60(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x3F98(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_29;                      // 0x4070(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x40A8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_28;                      // 0x4180(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_27;                      // 0x41B8(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_26;                      // 0x41F0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_6;                      // 0x4228(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_25;                      // 0x43C0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x43F8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x4420(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_24;                      // 0x44F8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x4530(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x4558(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x4580(0x0028)()
	uint8                                         Pad_45A8[0x8];                                     // 0x45A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_5;           // 0x45B0(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_4;           // 0x46F0(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult_2;            // 0x4830(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x4868(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_2;                 // 0x4890(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_23;                      // 0x4908(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x4940(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x4A18(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x4A50(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x4B28(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x4B60(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x4CF8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x4D30(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x4D58(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x4E30(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x4E68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x4E90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x4EB8(0x0028)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_3;           // 0x4EE0(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_2;           // 0x5020(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult_1;            // 0x5160(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x5198(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_1;                 // 0x51C0(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x5238(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x5270(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x5348(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x5380(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x5458(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x5490(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x5628(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x5660(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x5688(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x5760(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x5798(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x57C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x57E8(0x0028)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator_1;           // 0x5810(0x0140)()
	struct FAnimNode_TransitionPoseEvaluator      AnimGraphNode_TransitionPoseEvaluator;             // 0x5950(0x0140)()
	struct FAnimNode_StateResult                  AnimGraphNode_CustomTransitionResult;              // 0x5A90(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x5AC8(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x5AF0(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x5B68(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x5BA0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x5C78(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x5CB0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x5D88(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x5DC0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x5F58(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x5F90(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x5FB8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x6090(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x60C8(0x0198)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x6260(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x6288(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x62B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x62D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x6300(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x6328(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x6350(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x6378(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x63A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x63C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x63F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x6418(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x6440(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x6518(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x6550(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x6628(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x6660(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x6738(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x6770(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x6798(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x6870(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x68A8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x68D0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x69A8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x69E0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x6AB8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x6AF0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x6BC8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x6C00(0x0198)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x6D98(0x00B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x6E48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x6E70(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x6E98(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x6F70(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x6FA8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x6FE0(0x0198)()
	struct FAnimNode_CombineCurves                AnimGraphNode_CombineCurves;                       // 0x7178(0x0060)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x71D8(0x0038)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_1;                   // 0x7210(0x00C0)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x72D0(0x00C0)()
	EPerformanceRoleState                         StateInternal;                                     // 0x7390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          reLoop;                                            // 0x7391(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bForceChange;                                      // 0x7392(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7393[0x1];                                     // 0x7393(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Delta_Time_X;                                      // 0x7394(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HeadAlpha;                                         // 0x7398(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_739C[0x4];                                     // 0x739C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnEffectBegin;                                     // 0x73A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnEffectEnd;                                       // 0x73B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	float                                         PerformDelay;                                      // 0x73C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurPerformTime;                                    // 0x73C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bForceChange_Perform;                              // 0x73C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_73C9[0x3];                                     // 0x73C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CacheViewportSize;                                 // 0x73CC(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                LookAtWorld_Position;                              // 0x73D4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Mesh;                                              // 0x73E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                LookAtDirection;                                   // 0x73E8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCreateRoleState;                                 // 0x73F4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_73F5[0x3];                                     // 0x73F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CreateRoleStartLocation;                           // 0x73F8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CreateRoleEndLocation;                             // 0x7404(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CreateRoleMoveAllTime;                             // 0x7410(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7414[0x4];                                     // 0x7414(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsUiSceneRoleActor_C*                  Actor;                                             // 0x7418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CreateRoleMoveCurrentTime;                         // 0x7420(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CreateRoleStartRotation;                           // 0x7424(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                CreateRoleEndLocationOffset;                       // 0x7430(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CreateRoleEndRotation;                             // 0x743C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FRotator                               CreateRoleEndRotationOffset;                       // 0x7448(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         CreateRoleMovePlayRate;                            // 0x7454(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasInitCreateRoleInfo;                             // 0x7458(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          isLooping;                                         // 0x7459(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bInitCreateRoleInfo;                               // 0x745A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          InSkillRotate;                                     // 0x745B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          InSkillEndRotate;                                  // 0x745C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          TempRotate;                                        // 0x745D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_745E[0x2];                                     // 0x745E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSPerformanceRoleInfo                  PerformanceRoleInfo;                               // 0x7460(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BlinkAlpha;                                        // 0x7468(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InBlinking;                                        // 0x746C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_746D[0x3];                                     // 0x746D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BlinkEndTime;                                      // 0x7470(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         眨眼动画时长;                                      // 0x7474(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         此轮眨眼动画总时长;                                // 0x7478(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_747C[0x4];                                     // 0x747C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EPerformanceRoleState>                 SameStateArray01;                                  // 0x7480(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          False;                                             // 0x7490(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          DirectEnterLoop;                                   // 0x7491(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EPerformanceRoleState                         CurrentState;                                      // 0x7492(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          reLoopFromLoopToStart;                             // 0x7493(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bForceEnterLoop;                                   // 0x7494(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_PerformanceRole(int32 EntryPoint);
	void AnimNotify_LeaveCommonNotify();
	void AnimNotify_EnterDocument();
	void AnimNotify_EnterDocumentVoice();
	void AnimNotify_EnterDocumentAction();
	void AnimNotify_EnterIdle();
	void AnimNotify_EnterWeapon();
	void AnimNotify_EnterChip();
	void AnimNotify_EnterRoleElement();
	void AnimNotify_EnterRoleElementStand();
	void AnimNotify_EnterResonce();
	void AnimNotify_EnterRoleBreach();
	void AnimNotify_EnterAttribute();
	void AnimNotify_EnterSkill();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_ED21A98E48FA85555EA0D4A7C2A13D4F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_1B4EAA5848C16EDBEFB00FB24D38B27F();
	void AnimNotify_SkillEndBegin();
	void AnimNotify_LeaveLoop();
	void AnimNotify_EnterLoop();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_BC9EBC4944D2E109BC5CAA94C70EB8BC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_F6F9F8DC40D588C967DF2B9A41C97C25();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_83BA3C6F46EB8037E9C60BB9BDA31608();
	void BlueprintInitializeAnimation();
	void AnimNotify_EnterPerformIdle();
	void AnimNotify_LeaveOneLoopAction();
	void AnimNotify_EnterCommonNotify();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_D7436D7443A480F5FAF15A882087F30F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_2964307E48D5040F742A49B35F13F408();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_41DFE03F48C3833355C616B28AAF5009();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_E88CAB8D428F886DE51EB5A9BE372770();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_2C2EF99049E4EE2383BBD8B2786A4567();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_BB9DF0D54320499047A5319654D5DC2E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_05AA19EC4BA5688F5DC376ABA8F556E9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_9C35D5CF4052F823573EDCA339C5BC95();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_A59B1C3E413B4FF0E0A40C8A4E1608A4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3544AA1645E0CF5C1B631BBF34548087();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3A2D0019410882106E3D5AA8D6F2C19E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_7B44C6194963AAC6D793758E0821AA37();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3BAA36394ACE885F5D49E6B207A23E6C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_BC16130F44311D0DCB5B3590AECBE007();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_81008DE54870516BAB6E5E90973EF5C6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_87A017DC465C0B783BDB8793686B2399();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3921814044F2A49574F5B4B48102EC67();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_FA89A36640926C129757FAA49AF6A81A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_DEAF3D294066272ACE060C9862C527BD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_252C9B604DA355A186FC139923D59B56();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_B66CA673436FECF98D604D97A2B6C06A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_7331EF0C4FCC8260EC07C4B64D3B1D31();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_2A9BD4814CE11A56D9F8B5AD28BCDB54();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_B16644EE4359CE65D1A16BA8DE0E6A01();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_7EAEA40441EE79176E27DFA6B4F9FFC5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_0EDB639B401750A5D4E478B1823AE6FC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3D8EDC0949A468E4288C94B5166CDF2E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_FAF7A35C48527E1EA6A4AAB20EA2F436();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_C03E217044F8BF62D9BDACB1542C2794();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_24C99C61467D0205D123EC9AF5E06C23();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3FE8E3C646A416753DEE2AA221F25FA6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_481747314088EF8A503B2B82F47812FC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_30B0B6454BB641F81FA89F95CA2E7A79();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_56C6ACAC4E6FDEC24A16658E3730D394();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_942EF62C4B629FF8B62DE58BA4978BE1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_D4C08C6346453FFFCC8A24BBA1C4CA70();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_9DF1923C49FACD33DB7996B4F88AA35F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_9B9A0DA843AEF6FCA8E554BC94E139A1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_04D89DC14225578F83587E82FEB8F549();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_5BC208AA421FCBC084C7A7B465D64E0E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_D841EEBF4C3AAEE4FA4E22A41EEED9B6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_5D88DA9A4E6CB0EE56C4F48CD32B926A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_EF7B72AA40DDC31C385F22A6D2312B57();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_3DADD4CD489C57336548428E9B1B930E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_2FC853114BF83C19B08BFA8A8E704810();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_A0B917284B95FD2DCEAED29BE0D5525E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_DB55A1AE4A9423A5C47525A74E58BEB7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_4AEEB993432FEF9CF04A43AFC809B4FC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_73AE160147ADB36045B8D9A31DC6AF15();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_CC733D604E95BE7D9DFA349B1A5B704D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_52B4B2CB407931033523C9A14696E52E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_0F4FD3374213D4A81960F6A629673AFD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_83C90D9A461EF15044A8378A68A6F1E7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_1076956541FC74BF7A3047BF3518CA89();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_C60CCB8046FAB6F0C07D51B6B238E4BA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PerformanceRole_AnimGraphNode_TransitionResult_7A87E8194AFB02D1564F408592A3BAE7();
	void SetState(EPerformanceRoleState State, bool reLoop_0, bool reLoopFromLoopToStart_0, bool WaitLaseStateEnd);
	float GetHeadApha();
	void UpdateHeadRotator();
	void SyncAnimInstance(class UABP_PerformanceRole_C* SourceAnimInstance);
	void SetPerformDelay(float PerformTime);
	void UpdatePerfromTime();
	void UpdateLookAtRotation();
	void DebugLine(const struct FVector& LineStart, const struct FVector& LineEnd, const struct FLinearColor& LineColor);
	void UpdateCreateRoleLocation();
	void ClearCreateRoleState();
	void GetIsLooping(bool* isLooping_0);
	void SkillRotate();
	void UpdateBlinkInfo();
	bool Is_Same_State(EPerformanceRoleState NewState, const EPerformanceRoleState& StateInternal_0);
	void Set_Current_State(EPerformanceRoleState state);
	void TryForceEnterLoop();
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BasePose(struct FPoseLink* BasePose_0);
	void PostProcessPose(const struct FPoseLink& InPose, struct FPoseLink* PostProcessPose_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_PerformanceRole_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_PerformanceRole_C")
	}
	static class UABP_PerformanceRole_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_PerformanceRole_C>();
	}
};
DUMPER7_ASSERTS_UABP_PerformanceRole_C;

SDK_NAMESPACE_END
