#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ani_ErrSubmit_Close

#include "Basic.hpp"

#include "Ani_ErrSubmit_Close_classes.hpp"
#include "Ani_ErrSubmit_Close_parameters.hpp"


SDK_NAMESPACE_START

// Function Ani_ErrSubmit_Close.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_ErrSubmit_Close::USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_ErrSubmit_Close.SequenceDirector_C.UiItem_ErrSubmit_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_ErrSubmit                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_ErrSubmit_Close::USequenceDirector_C::UiItem_ErrSubmit_Event_0(class AUIContainerActor* UiItem_ErrSubmit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "UiItem_ErrSubmit_Event_0");

	Params::SequenceDirector_C_UiItem_ErrSubmit_Event_0 Parms{};

	Parms.UiItem_ErrSubmit = UiItem_ErrSubmit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_ErrSubmit_Close.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_ErrSubmit                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_ErrSubmit_Close::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0(class AUIContainerActor* UiItem_ErrSubmit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 Parms{};

	Parms.UiItem_ErrSubmit = UiItem_ErrSubmit;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
