#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Base_Nvzhu

#include "Basic.hpp"

#include "TsBaseCharacter_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Base_Nvzhu.BP_Base_Nvzhu_C
// 0x0020 (0x0780 - 0x0760)
class ABP_Base_Nvzhu_C : public ATsBaseCharacter_C
{
public:
	class UKuroAdjustableCapsuleComponent*        Bip001LThighTwist;                                 // 0x0758(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UKuroAdjustableCapsuleComponent*        Bip001RThighTwist;                                 // 0x0760(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UKuroAdjustableCapsuleComponent*        Bip001Spine2;                                      // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 WeaponCase1;                                       // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 WeaponCase0;                                       // 0x0778(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void FightCommand(bool isInAir);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Base_Nvzhu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Base_Nvzhu_C")
	}
	static class ABP_Base_Nvzhu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Base_Nvzhu_C>();
	}
};
DUMPER7_ASSERTS_ABP_Base_Nvzhu_C;

SDK_NAMESPACE_END
