#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BasePathLine_Edgewall_3_1

#include "Basic.hpp"

#include "BP_BasePathLine_Edgewall_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BasePathLine_Edgewall_3-1.BP_BasePathLine_Edgewall_3-1_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_BasePathLine_Edgewall_3_1_C final : public ABP_BasePathLine_Edgewall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BasePathLine_Edgewall_3-1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BasePathLine_Edgewall_3-1_C")
	}
	static class ABP_BasePathLine_Edgewall_3_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BasePathLine_Edgewall_3_1_C>();
	}
};
DUMPER7_ASSERTS_ABP_BasePathLine_Edgewall_3_1_C;

SDK_NAMESPACE_END
