#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CustomDepthForToon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CustomDepthForToon.BP_CustomDepthForToon_C
// 0x0010 (0x03D8 - 0x03C8)
class ABP_CustomDepthForToon_C final : public AKuroEditorTickActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CustomDepthForToon(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveDestroyed();
	void EnableCustomDepthForToon();
	void DisableCustomDepthForToon();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CustomDepthForToon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CustomDepthForToon_C")
	}
	static class ABP_CustomDepthForToon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CustomDepthForToon_C>();
	}
};
DUMPER7_ASSERTS_ABP_CustomDepthForToon_C;

SDK_NAMESPACE_END
