#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DollActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DollActor.BP_DollActor_C
// 0x00D0 (0x0488 - 0x03B8)
class ABP_DollActor_C final : public AKuroBPActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UChildActorComponent*                   PermanentEffect1;                                  // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   PermanentEffect;                                   // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         Id;                                                // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3DC[0x4];                                      // 0x03DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UEffectModelGroup_C>     GrabEffect;                                        // 0x03E0(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UEffectModelGroup_C>     GrabEndlessEffect;                                 // 0x0410(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UEffectModelGroup_C>     SpawnEffect;                                       // 0x0440(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          MainDoll;                                          // 0x0470(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_471[0x7];                                      // 0x0471(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequence*                          DollIdleAnim;                                      // 0x0478(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          DollGrabAnim;                                      // 0x0480(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DollActor(int32 EntryPoint);
	void PlayGrabEffectByTransform(bool IsEndless, const struct FTransformDouble& Transform);
	void TogglePlayGrabAnim(bool Enable, float Rate);
	void TogglePlayShow(bool Toggle, float PlayRate);
	void ResetPhysics();
	void SetPhysicsParameters(float AngularDamping, float LineraDamping);
	void PlaySpawnEffect();
	void PlayGrabEffect(bool IsEndless, const struct FVectorDouble& Location);
	void SetVisible(bool ToggleVisibility, bool TogglePhysics);
	void ReceiveBeginPlay();
	void PlayTimeEffect();
	void PlayGrabEffectByLocation(const struct FVectorDouble& Location);
	void SetPermanentEffect(bool Visibility, const class FString& Reason);
	void EnableRagdoll(bool Enable);
	void TogglePlayIdleAnim(bool toggle);
	void PlayGrabAnim();
	void SetSimulatePhysics(bool Enable);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DollActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DollActor_C")
	}
	static class ABP_DollActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DollActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_DollActor_C;

SDK_NAMESPACE_END
