#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicInteractProxy

#include "Basic.hpp"

#include "KuroGameBudget_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicInteractProxy.BP_PhysicInteractProxy_C
// 0x0008 (0x03C0 - 0x03B8)
class ABP_PhysicInteractProxy_C final : public AKuroGameBudgetBlueprintActor
{
public:
	class UCapsuleComponent*                      Capsule;                                           // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void SetRadiusAndHeight(float radius, float height);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicInteractProxy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicInteractProxy_C")
	}
	static class ABP_PhysicInteractProxy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicInteractProxy_C>();
	}
};
DUMPER7_ASSERTS_ABP_PhysicInteractProxy_C;

SDK_NAMESPACE_END
