#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PerformanceDisableLight

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PerformanceDisableLight.BP_PerformanceDisableLight_C
// 0x0020 (0x03E8 - 0x03C8)
class ABP_PerformanceDisableLight_C final : public AKuroEditorTickActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         SceneLightIntensity;                               // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash)
	float                                         ToonLightIntensity;                                // 0x03DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash)
	bool                                          DisableLight_Store;                                // 0x03E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, Interp, NoDestructor)
	bool                                          DisableLight;                                      // 0x03E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor)
	bool                                          DisableToonLight;                                  // 0x03E2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor)
	bool                                          DisableToonLight_Store;                            // 0x03E3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, Interp, NoDestructor)

public:
	void ExecuteUbergraph_BP_PerformanceDisableLight(int32 EntryPoint);
	void ReceiveDestroyed();
	void EditorTick(float DeltaSeconds);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void DisableLightFun();
	void DisableToonLightFun();
	void TickFunction();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PerformanceDisableLight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PerformanceDisableLight_C")
	}
	static class ABP_PerformanceDisableLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PerformanceDisableLight_C>();
	}
};
DUMPER7_ASSERTS_ABP_PerformanceDisableLight_C;

SDK_NAMESPACE_END
