#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SceneCapture_3To2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SceneCapture_3To2.BP_SceneCapture_3To2_C
// 0x0088 (0x0450 - 0x03C8)
class ABP_SceneCapture_3To2_C final : public AKuroEditorTickActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneCaptureComponent2D*               SceneCaptureComponent2D;                           // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         HiddenActor;                                       // 0x03E0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	TArray<class AActor*>                         ActorPosition;                                     // 0x03F0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	bool                                          Capture;                                           // 0x0400(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_401[0x7];                                      // 0x0401(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AKuroPostProcessVolume*                 PPV;                                               // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTextureRenderTarget2D>  RTSoft;                                            // 0x0410(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                 RT;                                                // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          First;                                             // 0x0448(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_SceneCapture_3To2(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveDestroyed();
	void EditorTick(float DeltaSeconds);
	void Resume();
	void Pause();
	void Stop();
	void Start();
	void TickOutside();
	void CaptureScene_Running();
	void SetEnablePPV(float Enable3To2Toggle);
	void ClearRT();
	void AllowOcclusionQueries();
	void EnableToonDepth();
	void DisableToonDepth();
	void ShouldStopOnHide(bool* ret);

	void GetAoiRange(int32* ret) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SceneCapture_3To2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SceneCapture_3To2_C")
	}
	static class ABP_SceneCapture_3To2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SceneCapture_3To2_C>();
	}
};
DUMPER7_ASSERTS_ABP_SceneCapture_3To2_C;

SDK_NAMESPACE_END
