#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPEEnableFollowShooter

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum BPEEnableFollowShooter.BPEEnableFollowShooter
// NumValues: 0x0004
enum class EBPEEnableFollowShooter : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator2                           = 2,
	BPEEnableFollowShooter_MAX               = 3,
};

SDK_NAMESPACE_END
