#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPEFollowShooterAttachStrategy

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum BPEFollowShooterAttachStrategy.BPEFollowShooterAttachStrategy
// NumValues: 0x0003
enum class EBPEFollowShooterAttachStrategy : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	BPEFollowShooterAttachStrategy_MAX       = 2,
};

SDK_NAMESPACE_END
