#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Tick

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_Tick.BPI_Tick_C.Tick
// 0x0004 (0x0004 - 0x0000)
struct BPI_Tick_C_Tick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_Tick_C_Tick;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
