#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_SceneBp

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_SceneBp.BPI_SceneBp_C.ShouldStopOnHide
// 0x0001 (0x0001 - 0x0000)
struct BPI_SceneBp_C_ShouldStopOnHide final
{
public:
	bool                                          ret;                                               // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_SceneBp_C_ShouldStopOnHide;

// Function BPI_SceneBp.BPI_SceneBp_C.GetAoiRange
// 0x0004 (0x0004 - 0x0000)
struct BPI_SceneBp_C_GetAoiRange final
{
public:
	int32                                         ret;                                               // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_SceneBp_C_GetAoiRange;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
