#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_SE_RootType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_SE_RootType.E_SE_RootType
// NumValues: 0x0005
enum class E_SE_RootType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	E_SE_MAX                                 = 4,
};

SDK_NAMESPACE_END
