#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EActionPlan

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EActionPlan.EActionPlan
// NumValues: 0x0006
enum class EActionPlan : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	EActionPlan_MAX                          = 5,
};

SDK_NAMESPACE_END
