#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EBulletChildrenType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EBulletChildrenType.EBulletChildrenType
// NumValues: 0x0007
enum class EBulletChildrenType : uint8
{
	NewEnumerator4                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator5                           = 5,
	EBulletChildrenType_MAX                  = 6,
};

SDK_NAMESPACE_END
