#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EBulletDestOffset

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EBulletDestOffset.EBulletDestOffset
// NumValues: 0x0004
enum class EBulletDestOffset : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EBulletDestOffset_MAX                    = 3,
};

SDK_NAMESPACE_END
