#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EBulletSyncType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EBulletSyncType.EBulletSyncType
// NumValues: 0x0003
enum class EBulletSyncType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	EBulletSyncType_MAX                      = 2,
};

SDK_NAMESPACE_END
