#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ECustomCameraMode

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ECustomCameraMode.ECustomCameraMode
// NumValues: 0x0007
enum class ECustomCameraMode : uint8
{
	NewEnumerator2                           = 0,
	NewEnumerator3                           = 1,
	NewEnumerator4                           = 2,
	NewEnumerator5                           = 3,
	NewEnumerator6                           = 4,
	NewEnumerator7                           = 5,
	ECustomCameraMode_MAX                    = 6,
};

SDK_NAMESPACE_END
