#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EFishingSkillType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EFishingSkillType.EFishingSkillType
// NumValues: 0x0005
enum class EFishingSkillType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator4                           = 3,
	EFishingSkillType_MAX                    = 4,
};

SDK_NAMESPACE_END
