#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EMonsterDeathType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EMonsterDeathType.EMonsterDeathType
// NumValues: 0x0004
enum class EMonsterDeathType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator2                           = 1,
	NewEnumerator1                           = 2,
	EMonsterDeathType_MAX                    = 3,
};

SDK_NAMESPACE_END
