#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EndlessCity

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class EndlessCity.EndlessCityStreamingSourceManager
// 0x0050 (0x0300 - 0x02B0)
class AEndlessCityStreamingSourceManager final : public AActor
{
public:
	uint8                                         Pad_2B0[0x40];                                     // 0x02B0(0x0040)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SceneSize;                                         // 0x02F0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         CenterSafeRange;                                   // 0x02F4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2F8[0x1];                                      // 0x02F8(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	EStreamingSourcePriority                      Priority;                                          // 0x02F9(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bStreamingSourceShouldBlockOnSlowStreaming;        // 0x02FA(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2FB[0x5];                                      // 0x02FB(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EndlessCityStreamingSourceManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EndlessCityStreamingSourceManager")
	}
	static class AEndlessCityStreamingSourceManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEndlessCityStreamingSourceManager>();
	}
};
DUMPER7_ASSERTS_AEndlessCityStreamingSourceManager;

SDK_NAMESPACE_END
