#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EQtaConditionType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EQtaConditionType.EQtaConditionType
// NumValues: 0x0004
enum class EQtaConditionType : uint8
{
	NewEnumerator5                           = 0,
	NewEnumerator4                           = 1,
	NewEnumerator6                           = 2,
	EQtaConditionType_MAX                    = 3,
};

SDK_NAMESPACE_END
