#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ESkillBehaviorLocationForwardType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ESkillBehaviorLocationForwardType.ESkillBehaviorLocationForwardType
// NumValues: 0x0006
enum class ESkillBehaviorLocationForwardType : uint8
{
	NewEnumerator12                          = 0,
	NewEnumerator13                          = 1,
	NewEnumerator14                          = 2,
	NewEnumerator15                          = 3,
	NewEnumerator16                          = 4,
	ESkillBehaviorLocationForwardType_MAX    = 5,
};

SDK_NAMESPACE_END
