#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ESkillBehaviorBuffTargetType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ESkillBehaviorBuffTargetType.ESkillBehaviorBuffTargetType
// NumValues: 0x0003
enum class ESkillBehaviorBuffTargetType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	ESkillBehaviorBuffTargetType_MAX         = 2,
};

SDK_NAMESPACE_END
