#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ESkillTargetDirection

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ESkillTargetDirection.ESkillTargetDirection
// NumValues: 0x0006
enum class ESkillTargetDirection : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator5                           = 1,
	NewEnumerator4                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator6                           = 4,
	ESkillTargetDirection_MAX                = 5,
};

SDK_NAMESPACE_END
