#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ImposterManager

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum ImposterManager.EImposterMappingMode
// NumValues: 0x0003
enum class EImposterMappingMode : uint8
{
	FullSphere                               = 0,
	TiltedHemiOct                            = 1,
	EImposterMappingMode_MAX                 = 2,
};

// Enum ImposterManager.EImposterLoadState
// NumValues: 0x0005
enum class EImposterLoadState : uint8
{
	Unloaded                                 = 0,
	Loading                                  = 1,
	Loaded                                   = 2,
	Failed                                   = 3,
	EImposterLoadState_MAX                   = 4,
};

SDK_NAMESPACE_END
