#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ImposterManager

#include "Basic.hpp"

#include "ImposterManager_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Class ImposterManager.ImposterStreamingManager
// 0x02A8 (0x02F0 - 0x0048)
class UImposterStreamingManager final : public UTickableWorldSubsystem
{
public:
	uint8                                         Pad_48[0x290];                                     // 0x0048(0x0290)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 PoolHolderActor;                                   // 0x02D8(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UMaterialInterface*                     MasterMaterial;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UStaticMesh*                            ImposterPlaneMesh;                                 // 0x02E8(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ImposterStreamingManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ImposterStreamingManager")
	}
	static class UImposterStreamingManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UImposterStreamingManager>();
	}
};
DUMPER7_ASSERTS_UImposterStreamingManager;

// Class ImposterManager.ImposterHISMComponent
// 0x0010 (0x0880 - 0x0870)
class UImposterHISMComponent final : public UHierarchicalInstancedStaticMeshComponent
{
public:
	uint8                                         Pad_870[0x10];                                     // 0x0870(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ImposterHISMComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ImposterHISMComponent")
	}
	static class UImposterHISMComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UImposterHISMComponent>();
	}
};
DUMPER7_ASSERTS_UImposterHISMComponent;

// Class ImposterManager.ImposterMeshData
// 0x0078 (0x00B0 - 0x0038)
class UImposterMeshData final : public UDataAsset
{
public:
	float                                         ImposterSize;                                      // 0x0038(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                PivotOffset;                                       // 0x003C(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x8];                                       // 0x0048(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector4                               SwitchDistances;                                   // 0x0050(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ViewCount;                                         // 0x0060(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EImposterMappingMode                          MappingMode;                                       // 0x0064(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TiltDegrees;                                       // 0x0068(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           WinterLeafColor;                                   // 0x006C(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           SpringLeafColor;                                   // 0x007C(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           SummerLeafColor;                                   // 0x008C(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           AutumnLeafColor;                                   // 0x009C(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ImposterMeshData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ImposterMeshData")
	}
	static class UImposterMeshData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UImposterMeshData>();
	}
};
DUMPER7_ASSERTS_UImposterMeshData;

// Class ImposterManager.ImposterPoolHolder
// 0x0000 (0x02B0 - 0x02B0)
class AImposterPoolHolder final : public AActor
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ImposterPoolHolder")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ImposterPoolHolder")
	}
	static class AImposterPoolHolder* GetDefaultObj()
	{
		return GetDefaultObjImpl<AImposterPoolHolder>();
	}
};
DUMPER7_ASSERTS_AImposterPoolHolder;

// Class ImposterManager.KuroImposterVer2Component
// 0x0150 (0x07B0 - 0x0660)
class UKuroImposterVer2Component final : public UStaticMeshComponent
{
public:
	TWeakObjectPtr<class UStaticMeshComponent>    SourceComponent;                                   // 0x0660(0x0008)(Edit, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartDistance;                                     // 0x0668(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxDistance;                                       // 0x066C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSeasonalEnabled;                                  // 0x0670(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_671[0x3];                                      // 0x0671(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           InstanceTintColor;                                 // 0x0674(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExternalSourceVisibilityControl;                  // 0x0684(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_685[0xAB];                                     // 0x0685(0x00AB)(Fixing Size After Last Property [ Dumper-7 ])
	class UImposterMeshData*                      CachedMeshData;                                    // 0x0730(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_738[0x30];                                     // 0x0738(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	class UImposterHISMComponent*                 BoundHISMRaw;                                      // 0x0768(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_770[0x40];                                     // 0x0770(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroImposterVer2Component")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroImposterVer2Component")
	}
	static class UKuroImposterVer2Component* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroImposterVer2Component>();
	}
};
DUMPER7_ASSERTS_UKuroImposterVer2Component;

SDK_NAMESPACE_END
