#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroScene

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum KuroScene.EKuroAttachGroupActorType
// NumValues: 0x0003
enum class EKuroAttachGroupActorType : uint8
{
	StaticMesh                               = 0,
	Other                                    = 1,
	EKuroAttachGroupActorType_MAX            = 2,
};

SDK_NAMESPACE_END
