#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroRopeEffect

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Enum KuroRopeEffect.ERopeAxisMode
// NumValues: 0x0004
enum class ERopeAxisMode : uint8
{
	WorldUp                                  = 0,
	ActorUp                                  = 1,
	PrincipalAxis                            = 2,
	ERopeAxisMode_MAX                        = 3,
};

// ScriptStruct KuroRopeEffect.RopeControlPointSkinning
// 0x0010 (0x0010 - 0x0000)
struct FRopeControlPointSkinning final
{
public:
	int32                                         BoneIndex;                                         // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BoneLocalPosition;                                 // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FRopeControlPointSkinning;

// ScriptStruct KuroRopeEffect.RopeSkinningData
// 0x0020 (0x0020 - 0x0000)
struct FRopeSkinningData final
{
public:
	TArray<struct FRopeControlPointSkinning>      ControlPoints;                                     // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        LastWorldPositions;                                // 0x0010(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FRopeSkinningData;

// ScriptStruct KuroRopeEffect.VerletParticle
// 0x0028 (0x0028 - 0x0000)
struct FVerletParticle final
{
public:
	struct FVector                                Position;                                          // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                PreviousPosition;                                  // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AccumulatedTension;                                // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPinned;                                           // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FVerletParticle;

SDK_NAMESPACE_END
