#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LaunchScene

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LaunchScene.LaunchScene_C
// 0x0010 (0x02C8 - 0x02B8)
class ALaunchScene_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FTimerHandle                           SharpheralStartupTimerHandle;                      // 0x02C0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LaunchScene(int32 EntryPoint);
	void 轮询Sharphereal_是否Startup完成();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LaunchScene_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LaunchScene_C")
	}
	static class ALaunchScene_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALaunchScene_C>();
	}
};
DUMPER7_ASSERTS_ALaunchScene_C;

SDK_NAMESPACE_END
