#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SConDitionGroupType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum SConDitionGroupType.SConditionGroupType
// NumValues: 0x0003
enum class ESConditionGroupType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	SConditionGroupType_MAX                  = 2,
};

SDK_NAMESPACE_END
