#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sharphereal

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "DeveloperSettings_classes.hpp"
#include "Sharphereal_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class Sharphereal.CSharpBlueprintFunctionLibrary
// 0x0000 (0x0030 - 0x0030)
class UCSharpBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void CallCSharpFunction(const class FString& ImageName, const class FString& NameSpaceName, const class FString& ClassName, const class FString& MethodName, int32 ParamsCount, class UGameInstance* GameInstance);
	static void CSharpDoMain(class UGameInstance* GameInstance);
	static void CSharpTestSceneLogin(const class FString& LevelName);
	static bool HasCSharpEnvironmentInitialized();
	static bool HasEnableCSharpEnv();
	static bool HasSharpherealModuleGreyBoxHit();
	static bool HasSharpherealModuleStartup();
	static void InitializeMonoEnvironment();
	static void Test2(ETestEnumInt32BlueprintType TestEnumInt32BlueprintType);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CSharpBlueprintFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CSharpBlueprintFunctionLibrary")
	}
	static class UCSharpBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCSharpBlueprintFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UCSharpBlueprintFunctionLibrary;

// Class Sharphereal.CSharpGeneratedClass
// 0x0000 (0x0338 - 0x0338)
class UCSharpGeneratedClass final : public UBlueprintGeneratedClass
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CSharpGeneratedClass")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CSharpGeneratedClass")
	}
	static class UCSharpGeneratedClass* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCSharpGeneratedClass>();
	}
};
DUMPER7_ASSERTS_UCSharpGeneratedClass;

// Class Sharphereal.DelegateProxy
// 0x0078 (0x00A8 - 0x0030)
class UDelegateProxy final : public UObject
{
public:
	uint8                                         Pad_30[0x78];                                      // 0x0030(0x0078)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ProxyFunction0();
	void ProxyFunction1();
	void ProxyFunction10();
	void ProxyFunction100();
	void ProxyFunction101();
	void ProxyFunction102();
	void ProxyFunction103();
	void ProxyFunction104();
	void ProxyFunction105();
	void ProxyFunction106();
	void ProxyFunction107();
	void ProxyFunction108();
	void ProxyFunction109();
	void ProxyFunction11();
	void ProxyFunction110();
	void ProxyFunction111();
	void ProxyFunction112();
	void ProxyFunction113();
	void ProxyFunction114();
	void ProxyFunction115();
	void ProxyFunction116();
	void ProxyFunction117();
	void ProxyFunction118();
	void ProxyFunction119();
	void ProxyFunction12();
	void ProxyFunction120();
	void ProxyFunction121();
	void ProxyFunction122();
	void ProxyFunction123();
	void ProxyFunction124();
	void ProxyFunction125();
	void ProxyFunction126();
	void ProxyFunction127();
	void ProxyFunction13();
	void ProxyFunction14();
	void ProxyFunction15();
	void ProxyFunction16();
	void ProxyFunction17();
	void ProxyFunction18();
	void ProxyFunction19();
	void ProxyFunction2();
	void ProxyFunction20();
	void ProxyFunction21();
	void ProxyFunction22();
	void ProxyFunction23();
	void ProxyFunction24();
	void ProxyFunction25();
	void ProxyFunction26();
	void ProxyFunction27();
	void ProxyFunction28();
	void ProxyFunction29();
	void ProxyFunction3();
	void ProxyFunction30();
	void ProxyFunction31();
	void ProxyFunction32();
	void ProxyFunction33();
	void ProxyFunction34();
	void ProxyFunction35();
	void ProxyFunction36();
	void ProxyFunction37();
	void ProxyFunction38();
	void ProxyFunction39();
	void ProxyFunction4();
	void ProxyFunction40();
	void ProxyFunction41();
	void ProxyFunction42();
	void ProxyFunction43();
	void ProxyFunction44();
	void ProxyFunction45();
	void ProxyFunction46();
	void ProxyFunction47();
	void ProxyFunction48();
	void ProxyFunction49();
	void ProxyFunction5();
	void ProxyFunction50();
	void ProxyFunction51();
	void ProxyFunction52();
	void ProxyFunction53();
	void ProxyFunction54();
	void ProxyFunction55();
	void ProxyFunction56();
	void ProxyFunction57();
	void ProxyFunction58();
	void ProxyFunction59();
	void ProxyFunction6();
	void ProxyFunction60();
	void ProxyFunction61();
	void ProxyFunction62();
	void ProxyFunction63();
	void ProxyFunction64();
	void ProxyFunction65();
	void ProxyFunction66();
	void ProxyFunction67();
	void ProxyFunction68();
	void ProxyFunction69();
	void ProxyFunction7();
	void ProxyFunction70();
	void ProxyFunction71();
	void ProxyFunction72();
	void ProxyFunction73();
	void ProxyFunction74();
	void ProxyFunction75();
	void ProxyFunction76();
	void ProxyFunction77();
	void ProxyFunction78();
	void ProxyFunction79();
	void ProxyFunction8();
	void ProxyFunction80();
	void ProxyFunction81();
	void ProxyFunction82();
	void ProxyFunction83();
	void ProxyFunction84();
	void ProxyFunction85();
	void ProxyFunction86();
	void ProxyFunction87();
	void ProxyFunction88();
	void ProxyFunction89();
	void ProxyFunction9();
	void ProxyFunction90();
	void ProxyFunction91();
	void ProxyFunction92();
	void ProxyFunction93();
	void ProxyFunction94();
	void ProxyFunction95();
	void ProxyFunction96();
	void ProxyFunction97();
	void ProxyFunction98();
	void ProxyFunction99();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DelegateProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DelegateProxy")
	}
	static class UDelegateProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDelegateProxy>();
	}
};
DUMPER7_ASSERTS_UDelegateProxy;

// Class Sharphereal.JsBridgetBlueprintFunctionLibrary
// 0x0000 (0x0030 - 0x0030)
class UJsBridgetBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void CSharpCallJavascript(uint32 EventId, int32 TargetId, uint8 ParameterCount, uint64 ParameterBufferPtr);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JsBridgetBlueprintFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JsBridgetBlueprintFunctionLibrary")
	}
	static class UJsBridgetBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJsBridgetBlueprintFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UJsBridgetBlueprintFunctionLibrary;

// Class Sharphereal.KooSharpRuntimeSettings
// 0x0180 (0x01C8 - 0x0048)
class UKooSharpRuntimeSettings final : public UDeveloperSettings
{
public:
	TArray<EKooSharpBuildConfiguration>           EnableDebugger;                                    // 0x0048(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<EKooSharpBuildConfiguration>           WaitForDebugger;                                   // 0x0058(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	uint16                                        DebuggerPort;                                      // 0x0068(0x0002)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FKooSharpMonoTraceLevelRuntimeSettings MonoTraceLevel;                                    // 0x006A(0x0005)(Edit, Config, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_6F[0x1];                                       // 0x006F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKooSharpMonoTraceMaskRuntimeSettings  MonoTraceMask;                                     // 0x0070(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	int32                                         MonoDebuggerLogLevel;                              // 0x00C0(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 MonoDebuggerLogFile;                               // 0x00C8(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 MonoGCDebugArgs;                                   // 0x00D8(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<EKooSharpBuildConfiguration>           EnableMonoStatForMemory;                           // 0x00E8(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<EKooSharpBuildConfiguration>           EnableMonoStatForJIT;                              // 0x00F8(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<EKooSharpBuildConfiguration>           EnableMonoStatForGC;                               // 0x0108(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<EKooSharpBuildConfiguration>           EnableLogJitAddress;                               // 0x0118(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FString>                         ExtraMonoOptions;                                  // 0x0128(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	bool                                          bEnableCSharpEnvironment;                          // 0x0138(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseMMapLoadDLL;                                   // 0x0139(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13A[0x6];                                      // 0x013A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ScriptProjectName;                                 // 0x0140(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ScriptAssembliesPath;                              // 0x0150(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ScriptAssembliesEditorPath;                        // 0x0160(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ScriptAssembliesNonShippingPath;                   // 0x0170(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMonoAotMode                                  MonoAOTMode;                                       // 0x0180(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         EditorPreloadAssemblies;                           // 0x0188(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FString>                         RuntimeLoadAssemblies;                             // 0x0198(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FString>                         ExtraEnvironment;                                  // 0x01A8(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FString>                         NoUseDangerousInternalCall;                        // 0x01B8(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KooSharpRuntimeSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KooSharpRuntimeSettings")
	}
	static class UKooSharpRuntimeSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKooSharpRuntimeSettings>();
	}
};
DUMPER7_ASSERTS_UKooSharpRuntimeSettings;

// Class Sharphereal.SharpherealReflectionBPL
// 0x0000 (0x0030 - 0x0030)
class USharpherealReflectionBPL final : public UBlueprintFunctionLibrary
{
public:
	static void GetAllBlueprintProxy(TArray<class UClass*>* Classes);
	static bool GetClassDefine(class UClass* Class_0, struct FSharpherealReflectionClassGenerateDefine* OutDefine);
	static bool GetStructDefine(class UStruct* Struct, struct FSharpherealReflectionStructGenerateDefine* OutDefine);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SharpherealReflectionBPL")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SharpherealReflectionBPL")
	}
	static class USharpherealReflectionBPL* GetDefaultObj()
	{
		return GetDefaultObjImpl<USharpherealReflectionBPL>();
	}
};
DUMPER7_ASSERTS_USharpherealReflectionBPL;

// Class Sharphereal.ConsoleCommandBPL
// 0x0000 (0x0030 - 0x0030)
class UConsoleCommandBPL final : public UBlueprintFunctionLibrary
{
public:
	static bool GetConsoleBoolVariable(const class FString& Name_0, bool* Result);
	static bool GetConsoleFloatVariable(const class FString& Name_0, float* Result);
	static bool GetConsoleIntVariable(const class FString& Name_0, int32* Result);
	static bool GetConsoleStringVariable(const class FString& Name_0, class FString* Result);
	static void RegisterConsoleBoolVariable(const class FString& Name_0, bool DefaultValue, const class FString& Help, uint32 Flags_0);
	static void RegisterConsoleCommand(const class FString& Name_0, const class FString& Help, const TDelegate<void()>& Command, uint32 Flags_0);
	static void RegisterConsoleCommandWithArgs(const class FString& Name_0, const class FString& Help, const TDelegate<void(const TArray<class FString>& Args)>& Command, uint32 Flags_0);
	static void RegisterConsoleCommandWithWorld(const class FString& Name_0, const class FString& Help, const TDelegate<void(class UWorld* World)>& Command, uint32 Flags_0);
	static void RegisterConsoleCommandWithWorldAndArgs(const class FString& Name_0, const class FString& Help, const TDelegate<void(const TArray<class FString>& Args, class UWorld* World)>& Command, uint32 Flags_0);
	static void RegisterConsoleFloatVariable(const class FString& Name_0, float DefaultValue, const class FString& Help, uint32 Flags_0);
	static void RegisterConsoleIntVariable(const class FString& Name_0, int32 DefaultValue, const class FString& Help, uint32 Flags_0);
	static void RegisterConsoleStringVariable(const class FString& Name_0, const class FString& DefaultValue, const class FString& Help, uint32 Flags_0);
	static bool SetConsoleBoolVariable(const class FString& Name_0, bool Value, uint32 Flags_0);
	static bool SetConsoleFloatVariable(const class FString& Name_0, float Value, uint32 Flags_0);
	static bool SetConsoleIntVariable(const class FString& Name_0, int32 Value, uint32 Flags_0);
	static bool SetConsoleStringVariable(const class FString& Name_0, const class FString& Value, uint32 Flags_0);
	static void UnregisterConsoleObject(const class FString& Name_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ConsoleCommandBPL")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ConsoleCommandBPL")
	}
	static class UConsoleCommandBPL* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConsoleCommandBPL>();
	}
};
DUMPER7_ASSERTS_UConsoleCommandBPL;

SDK_NAMESPACE_END
