#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Splash

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct None.None
// 0x0018 (0x0018 - 0x0000)
struct FSplash final
{
public:
	class UTexture2D*                             value_3_0D5C89D24C7243E14F07EF81CAA61C07;          // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 path_6_6E4D30EE47AF016A024B5FB55CEF5DAC;           // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FSplash;

SDK_NAMESPACE_END
