#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyAddBuff

#include "Basic.hpp"

#include "TsAnimNotifyBase_classes.hpp"


SDK_NAMESPACE_START

// TypeScriptGeneratedClass TsAnimNotifyAddBuff.TsAnimNotifyAddBuff_C
// 0x0008 (0x0060 - 0x0058)
class UTsAnimNotifyAddBuff_C final : public UTsAnimNotifyBase_C
{
public:
	int64                                         BuffId;                                            // 0x0058(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool K2_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyAddBuff_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyAddBuff_C")
	}
	static class UTsAnimNotifyAddBuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyAddBuff_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyAddBuff_C;

SDK_NAMESPACE_END
