#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAxisHandle

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function TsAxisHandle.TsAxisHandle_C.OnInputAxis
// 0x0004 (0x0004 - 0x0000)
struct TsAxisHandle_C_OnInputAxis final
{
public:
	float                                         value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_TsAxisHandle_C_OnInputAxis;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
