#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsBaseVehicle

#include "Basic.hpp"

#include "TsBaseVehicle_classes.hpp"
#include "TsBaseVehicle_parameters.hpp"


namespace SDK
{

// Function TsBaseVehicle.TsBaseVehicle_C.ExecuteUbergraph_TsBaseVehicle
// (Final, Native, UbergraphFunction, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATsBaseVehicle_C::ExecuteUbergraph_TsBaseVehicle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsBaseVehicle_C", "ExecuteUbergraph_TsBaseVehicle");

	Params::TsBaseVehicle_C_ExecuteUbergraph_TsBaseVehicle Parms{};

	Parms.EntryPoint = EntryPoint;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TsBaseVehicle.TsBaseVehicle_C.ReceiveDestroyed
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void ATsBaseVehicle_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsBaseVehicle_C", "ReceiveDestroyed");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TsBaseVehicle.TsBaseVehicle_C.SetDitherEffect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Dither                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ECharacterDitherType                    DitherType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATsBaseVehicle_C::SetDitherEffect(float Dither, ECharacterDitherType DitherType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsBaseVehicle_C", "SetDitherEffect");

	Params::TsBaseVehicle_C_SetDitherEffect Parms{};

	Parms.Dither = Dither;
	Parms.DitherType = DitherType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TsBaseVehicle.TsBaseVehicle_C.GetEntityId
// (Native, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 ATsBaseVehicle_C::GetEntityId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsBaseVehicle_C", "GetEntityId");

	Params::TsBaseVehicle_C_GetEntityId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

