#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsHotPatchPanelConfig

#include "Basic.hpp"

#include "TsHotPatchPanelConfig_classes.hpp"
#include "TsHotPatchPanelConfig_parameters.hpp"


namespace SDK
{

// Function TsHotPatchPanelConfig.TsHotPatchPanelConfig_C.ExecuteUbergraph_TsHotPatchPanelConfig
// (Final, Native, UbergraphFunction, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTsHotPatchPanelConfig_C::ExecuteUbergraph_TsHotPatchPanelConfig(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsHotPatchPanelConfig_C", "ExecuteUbergraph_TsHotPatchPanelConfig");

	Params::TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig Parms{};

	Parms.EntryPoint = EntryPoint;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TsHotPatchPanelConfig.TsHotPatchPanelConfig_C.OnDisableBP
// (Native, Event, Public, Protected, BlueprintCallable, BlueprintEvent)

void UTsHotPatchPanelConfig_C::OnDisableBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsHotPatchPanelConfig_C", "OnDisableBP");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TsHotPatchPanelConfig.TsHotPatchPanelConfig_C.OnEnableBP
// (Native, Event, Public, Protected, BlueprintCallable, BlueprintEvent)

void UTsHotPatchPanelConfig_C::OnEnableBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsHotPatchPanelConfig_C", "OnEnableBP");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TsHotPatchPanelConfig.TsHotPatchPanelConfig_C.AwakeBP
// (Native, Event, Public, Protected, BlueprintCallable, BlueprintEvent)

void UTsHotPatchPanelConfig_C::AwakeBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsHotPatchPanelConfig_C", "AwakeBP");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

