#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsHotPatchPanelConfig

#include "Basic.hpp"


namespace SDK::Params
{

// Function TsHotPatchPanelConfig.TsHotPatchPanelConfig_C.ExecuteUbergraph_TsHotPatchPanelConfig
// 0x0004 (0x0004 - 0x0000)
struct TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig) == 0x000004, "Wrong alignment on TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig");
static_assert(sizeof(TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig) == 0x000004, "Wrong size on TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig");
static_assert(offsetof(TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig, EntryPoint) == 0x000000, "Member 'TsHotPatchPanelConfig_C_ExecuteUbergraph_TsHotPatchPanelConfig::EntryPoint' has a wrong offset!");

}

