#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsUiNavigationPanelConfig

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function TsUiNavigationPanelConfig.TsUiNavigationPanelConfig_C.ExecuteUbergraph_TsUiNavigationPanelConfig
// 0x0004 (0x0004 - 0x0000)
struct TsUiNavigationPanelConfig_C_ExecuteUbergraph_TsUiNavigationPanelConfig final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_TsUiNavigationPanelConfig_C_ExecuteUbergraph_TsUiNavigationPanelConfig;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
