#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsVehicleBlueprintFunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsVehicleBlueprintFunctionLibrary.TsVehicleBlueprintFunctionLibrary_C
// 0x0000 (0x0030 - 0x0030)
class UTsVehicleBlueprintFunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static void UpdateVehiclePerformData(int32 EntityId, bool& IsImpacted, float& Direction, float& Strength, class UObject* __WorldContext);
	static void UpdateAnimInfo(int32 EntityId, class UObject* __WorldContext);
	static bool GetAndResetEnterSprint(int32 EntityId, class UObject* __WorldContext);
	static void UpdateDrivedVehiclePerformData(int32 EntityId, bool& IsImpacted, float& Direction, float& Strength, class UObject* __WorldContext);
	static bool GetDrivedVehicleSeatRot(int32 EntityId, struct FRotator& OutRot, class UObject* __WorldContext);
	static float ConvertAngleToPassengerSpace(int32 EntityId, float YawInVehicleCoordinate, class UObject* __WorldContext);
	static bool GetDrivedVehicleVelocity(int32 EntityId, struct FVector& OutVelocity, class UObject* __WorldContext);
	static float GetDrivedVehicleRotiationSpeed(int32 EntityId, class UObject* __WorldContext);
	static bool GetVehicleVelocity(int32 EntityId, struct FVector& OutVelocity, class UObject* __WorldContext);
	static float GetVehicleRotiationSpeed(int32 EntityId, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TsVehicleBlueprintFunctionLibrary_C">();
	}
	static class UTsVehicleBlueprintFunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsVehicleBlueprintFunctionLibrary_C>();
	}
};
static_assert(alignof(UTsVehicleBlueprintFunctionLibrary_C) == 0x000008, "Wrong alignment on UTsVehicleBlueprintFunctionLibrary_C");
static_assert(sizeof(UTsVehicleBlueprintFunctionLibrary_C) == 0x000030, "Wrong size on UTsVehicleBlueprintFunctionLibrary_C");

}

