#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace ECharacterControllerUVSwitch { enum class ECharacterControllerUVSwitch : uint8; }

namespace Ani_ErrSubmit_Loop { class USequenceDirector_C; }

namespace Ani_ErrSubmit_Start { class USequenceDirector_C; }

namespace Ani_ErrSubmit_Close { class USequenceDirector_C; }

namespace KuroRenderingRuntimeBPPlugin { enum class ECharacterControllerUVSwitch : uint8; }

